#include "6502.h"

const char prefixes[57][3] =
{
    "???", "ADC", "AND", "ASL",
    "BCC", "BCS", "BEQ", "BIT", "BMI", "BNE", "BPL", "BRK", "BVC", "BVS",
    "CLC", "CLD", "CLI", "CLV", "CMP", "CPX", "CPY",
    "DEC", "DEX", "DEY", "EOR", "INC", "INX", "INY", "JMP", "JSR",
    "LDA", "LDX", "LDY", "LSR", "NOP", "ORA", "PHA", "PHP", "PLA", "PLP",
    "ROL", "ROR", "RTI", "RTS", "SBC", "SEC", "SED", "SEI", "STA", "STX", "STY",
    "TAX", "TAY", "TSX", "TXA", "TXS", "TYA"
};

const Operation_t opcodes[256] =
{
    {PREFIX_BRK,ADDRESSING_IMPLIED,1,7},
    {PREFIX_ORA,ADDRESSING_INDIRECT_PREINDEXED,2,6},
    {0}, // 0x02
    {0},
    {0},
    {PREFIX_ORA,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_ASL,ADDRESSING_ABSOLUTE_ZEROPAGE,2,5},
    {0}, // 0x07
    {PREFIX_PHP,ADDRESSING_IMPLIED,1,3},
    {PREFIX_ORA,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_ASL,ADDRESSING_ACCUMULATOR,1,2},
    {0}, // 0x0B
    {0},
    {PREFIX_ORA,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_ASL,ADDRESSING_ABSOLUTE,3,6},
    {0}, // 0x0F
    {PREFIX_BPL,ADDRESSING_RELATIVE,2,2},
    {PREFIX_ORA,ADDRESSING_INDIRECT_POSTINDEXED,2,5},
    {0}, // 0x12
    {0},
    {0},
    {PREFIX_ORA,ADDRESSING_INDEXED_ZEROPAGE,2,4},
    {PREFIX_ASL,ADDRESSING_INDEXED_ZEROPAGE,2,6},
    {0}, // 0x17
    {PREFIX_CLC,ADDRESSING_IMPLIED,1,2},
    {PREFIX_ORA,ADDRESSING_INDEXED_Y,3,4},
    {0}, // 0x1A
    {0},
    {0},
    {PREFIX_ORA,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_ASL,ADDRESSING_INDEXED_X,3,7},
    {0}, // 0x1F
    {PREFIX_JSR,ADDRESSING_IMPLIED,3,6},
    {PREFIX_AND,ADDRESSING_INDIRECT_PREINDEXED,2,6},
    {0}, // 0x22
    {0},
    {PREFIX_BIT,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_AND,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_ROL,ADDRESSING_ABSOLUTE_ZEROPAGE,2,5},
    {0}, // 0x27
    {PREFIX_PLP,ADDRESSING_IMPLIED,1,4},
    {PREFIX_AND,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_ROL,ADDRESSING_ACCUMULATOR,1,2},
    {0}, // 0x2B
    {PREFIX_BIT,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_AND,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_ROL,ADDRESSING_ABSOLUTE,3,6},
    {0}, // 0x2F
    {PREFIX_BMI,ADDRESSING_RELATIVE,2,2},
    {PREFIX_AND,ADDRESSING_INDIRECT_POSTINDEXED,2,5},
    {0}, // 0x32
    {0},
    {0},
    {PREFIX_AND,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_ROL,ADDRESSING_INDEXED_ZEROPAGE_X,2,6},
    {0}, // 0x37
    {PREFIX_SEC,ADDRESSING_IMPLIED,1,2},
    {PREFIX_AND,ADDRESSING_INDEXED_Y,3,4},
    {0}, // 0x3A
    {0},
    {0},
    {PREFIX_AND,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_ROL,ADDRESSING_INDEXED_X,3,7},
    {0}, // 0x3F
    {PREFIX_RTI,ADDRESSING_IMPLIED,1,6},
    {PREFIX_EOR,ADDRESSING_INDIRECT_PREINDEXED,2,6},
    {0}, // 0x42
    {0},
    {0},
    {PREFIX_EOR,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_LSR,ADDRESSING_ABSOLUTE_ZEROPAGE,2,5},
    {0}, // 0x47
    {PREFIX_PHA,ADDRESSING_IMPLIED,1,3},
    {PREFIX_EOR,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_LSR,ADDRESSING_ACCUMULATOR,1,2},
    {0}, // 0x4B
    {PREFIX_JMP,ADDRESSING_ABSOLUTE,3,3},
    {PREFIX_EOR,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_LSR,ADDRESSING_ABSOLUTE,3,6},
    {0}, // 0x4F
    {PREFIX_BVC,ADDRESSING_RELATIVE,2,2},
    {PREFIX_EOR,ADDRESSING_INDIRECT_POSTINDEXED,2,5},
    {0}, // 0x52
    {0},
    {0},
    {PREFIX_EOR,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_LSR,ADDRESSING_INDEXED_ZEROPAGE_X,2,6},
    {0}, // 0x57
    {PREFIX_CLI,ADDRESSING_IMPLIED,1,2},
    {PREFIX_EOR,ADDRESSING_INDEXED_Y,3,4},
    {0},
    {0},
    {0}, // 0x5C
    {PREFIX_EOR,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_LSR,ADDRESSING_INDEXED_X,3,7},
    {0}, // 0x5F
    {PREFIX_RTS,ADDRESSING_IMPLIED,1,6},
    {PREFIX_ADC,ADDRESSING_INDIRECT_PREINDEXED,2,6},
    {0}, // 0x62
    {0},
    {0},
    {PREFIX_ADC,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_ROR,ADDRESSING_ABSOLUTE_ZEROPAGE,2,5},
    {0}, // 0x67
    {PREFIX_PLA,ADDRESSING_IMPLIED,1,4},
    {PREFIX_ADC,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_ROR,ADDRESSING_ACCUMULATOR,1,2},
    {0}, // 0x6B
    {PREFIX_JMP,ADDRESSING_INDIRECT,3,5},
    {PREFIX_ADC,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_ROR,ADDRESSING_ABSOLUTE,3,6},
    {0}, // 0x6F
    {PREFIX_BVS,ADDRESSING_RELATIVE,2,2},
    {PREFIX_ADC,ADDRESSING_INDIRECT_POSTINDEXED,2,5},
    {0}, // 0x72
    {0},
    {0},
    {PREFIX_ADC,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_ROR,ADDRESSING_INDEXED_ZEROPAGE_X,2,6},
    {0}, // 0x77
    {PREFIX_SEI,ADDRESSING_IMPLIED,1,2},
    {PREFIX_ADC,ADDRESSING_INDEXED_Y,0,0},
    {0}, // 0x7A
    {0},
    {0},
    {PREFIX_ADC,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_ROR,ADDRESSING_INDEXED_X,3,7},
    {0}, // 0x7F
    {0}, // 0x80
    {PREFIX_STA,ADDRESSING_INDIRECT_PREINDEXED,2,6},
    {0}, // 0x82
    {0},
    {PREFIX_STY,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_STA,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_STX,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {0}, // 0x87
    {PREFIX_DEY,ADDRESSING_IMPLIED,1,2},
    {0}, // 0x89
    {PREFIX_TXA,ADDRESSING_IMPLIED,1,2},
    {0}, // 0x8B
    {PREFIX_STY,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_STA,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_STX,ADDRESSING_ABSOLUTE,3,4},
    {0}, // 0x8F
    {PREFIX_BCC,ADDRESSING_RELATIVE,2,2},
    {PREFIX_STA,ADDRESSING_INDIRECT_POSTINDEXED,2,6},
    {0}, // 0x92
    {0},
    {PREFIX_STY,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_STA,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_STX,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {0}, // 0x97
    {PREFIX_TYA,ADDRESSING_IMPLIED,1,2},
    {PREFIX_STA,ADDRESSING_INDEXED_Y,3,5},
    {PREFIX_TXS,ADDRESSING_IMPLIED,1,2},
    {0}, // 0x9B
    {0},
    {PREFIX_STA,ADDRESSING_INDEXED_X,3,5},
    {0}, // 0x9E
    {0}, // 0x9F
    {PREFIX_LDY,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_LDA,ADDRESSING_INDIRECT_POSTINDEXED,2,6},
    {PREFIX_LDX,ADDRESSING_IMMEDIATE,2,2},
    {0}, // 0xA3
    {PREFIX_LDY,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_LDA,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_LDX,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {0}, // 0xA7
    {PREFIX_TAY,ADDRESSING_IMPLIED,1,2},
    {PREFIX_LDA,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_TAX,ADDRESSING_IMPLIED,1,2},
    {0}, // 0x AB
    {PREFIX_LDY,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_LDA,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_LDX,ADDRESSING_ABSOLUTE,3,4},
    {0}, // 0xAF
    {PREFIX_BCS,ADDRESSING_RELATIVE,2,2},
    {PREFIX_LDA,ADDRESSING_INDIRECT_POSTINDEXED,2,5},
    {0}, // 0xB2
    {0},
    {PREFIX_LDY,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_LDA,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_LDX,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {0}, // 0xB7
    {PREFIX_CLV,ADDRESSING_IMPLIED,1,2},
    {PREFIX_LDA,ADDRESSING_INDEXED_Y,3,4},
    {PREFIX_TSX,ADDRESSING_IMPLIED,1,2},
    {0}, // 0xBB
    {PREFIX_LDY,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_LDA,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_LDX,ADDRESSING_INDEXED_X,3,4},
    {0}, // 0xBF
    {PREFIX_CPY,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_CMP,ADDRESSING_INDIRECT_PREINDEXED,2,6},
    {0}, // 0xC2
    {0},
    {PREFIX_CPY,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_CMP,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_DEC,ADDRESSING_ABSOLUTE_ZEROPAGE,2,5},
    {0}, // 0xC7
    {PREFIX_INY,ADDRESSING_IMPLIED,1,2},
    {PREFIX_CMP,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_DEX,ADDRESSING_IMPLIED,1,2},
    {0}, // 0xCB
    {PREFIX_CPY,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_CMP,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_DEC,ADDRESSING_ABSOLUTE,3,6},
    {0}, // 0xCF
    {PREFIX_BNE,ADDRESSING_RELATIVE,2,2},
    {PREFIX_CMP,ADDRESSING_INDIRECT_POSTINDEXED,2,5},
    {0}, // 0xD2
    {0},
    {0},
    {PREFIX_CMP,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_DEC,ADDRESSING_INDEXED_ZEROPAGE_X,2,6},
    {0}, // 0xD7
    {PREFIX_CLD,ADDRESSING_IMPLIED,1,2},
    {PREFIX_CMP,ADDRESSING_INDEXED_Y,3,4},
    {0}, // 0xDA
    {0},
    {0},
    {PREFIX_CMP,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_DEC,ADDRESSING_INDEXED_X,3,7},
    {0}, // 0xDF
    {PREFIX_CPX,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_SBC,ADDRESSING_INDIRECT_PREINDEXED,2,6},
    {0}, // 0xE2
    {0},
    {PREFIX_CPX,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_SBC,ADDRESSING_ABSOLUTE_ZEROPAGE,2,3},
    {PREFIX_INC,ADDRESSING_ABSOLUTE_ZEROPAGE,2,5},
    {0}, // 0xE7
    {PREFIX_INX,ADDRESSING_IMPLIED,1,2},
    {PREFIX_SBC,ADDRESSING_IMMEDIATE,2,2},
    {PREFIX_NOP,ADDRESSING_IMPLIED,1,2},
    {0}, // 0xEB
    {PREFIX_CPX,ADDRESSING_ABSOLUTE,2,4},
    {PREFIX_SBC,ADDRESSING_ABSOLUTE,3,4},
    {PREFIX_INC,ADDRESSING_ABSOLUTE,3,6},
    {0}, // 0xEF
    {PREFIX_BEQ,ADDRESSING_RELATIVE,2,2},
    {PREFIX_SBC,ADDRESSING_INDIRECT_POSTINDEXED,2,5},
    {0}, // 0xF2
    {0},
    {0},
    {PREFIX_SBC,ADDRESSING_INDEXED_ZEROPAGE_X,2,4},
    {PREFIX_INC,ADDRESSING_INDEXED_ZEROPAGE_X,2,6},
    {0}, // 0xF7
    {PREFIX_SED,ADDRESSING_IMPLIED,1,2},
    {PREFIX_SBC,ADDRESSING_INDEXED_Y,3,4},
    {0}, // 0xFA
    {0},
    {0},
    {PREFIX_SBC,ADDRESSING_INDEXED_X,3,4},
    {PREFIX_INC,ADDRESSING_INDEXED_X,3,7},
    {0}, // 0xFF
};
